mosip/kattu

.github/workflows/docker-build.yml

Skip docker login and docker push if PR event called

[MOSIP-25631] Updated docker-build.yml

---

.github/workflows/release-changes.yml

[MOSIP-29363] Added checks toif the *SNAPSHOT is present in the dependency section of the POM file.

---

.github/workflows/gradlew-sonar-analysis.yml

[MOSIP-29145] Updated gradlew-sonar-analysis.yml

---

.github/workflows/clear-artifacts.yml

[MOSIP-29257] Added clear-artifacts.yml

---

.github/workflows/codeql-analysis.yml

[MOSIP-29168] Added codeql-analysis.yml

---

.github/workflows/npm-sonar-analysis.yml

[MOSIP-29143] Updated npm-sonar-analysis.yml

---

.github/workflows/clear-artifacts.yml

[MOSIP-29143] Updated clear-artifacts.yml

---

.github/workflows/gradlew-sonar-analysis.yml
.github/workflows/npm-andriod-build.yml
.github/workflows/npm-build.yml
.github/workflows/npm-publish-to-npm-registry.yml

[MOSIP-29145] Fixed android workflow issues

---

.github/workflows/npm-andriod-build.yml
.github/workflows/npm-publish-to-npm-registry.yml

[MOSIP-29251] Updated npm workflows to skip gradlew build

---

.github/workflows/tag.yml
docs/tag-readme.md

[MOSIP-30055] Updated tag.yml and tag-readme.md

---

.github/workflows/android-publish.yml
.github/workflows/chart-lint-publish.yml
.github/workflows/db-test.yml
.github/workflows/dev-check.yml
.github/workflows/docker-build.yml
.github/workflows/gradlew-sonar-analysis.yml
.github/workflows/image-transfer.yml
.github/workflows/ios-publish.yml
.github/workflows/maven-build.yml
.github/workflows/maven-publish-to-nexus.yml
.github/workflows/maven-sonar-analysis.yml
.github/workflows/npm-android-build.yml
.github/workflows/npm-build.yml
.github/workflows/npm-publish-to-npm-registry.yml
.github/workflows/npm-sonar-analysis.yml
.github/workflows/release-changes.yml
.github/workflows/tag.yaml

PR - pull request
(cherry picked from commit 4a6bcc867e440681e824c71cc31c1b68997a0f69)

[DSD-4139] Added condition to skip slack notification for PR

---

.github/workflows/android-publish.yml
.github/workflows/chart-lint-publish.yml
.github/workflows/db-test.yml
.github/workflows/dev-check.yml
.github/workflows/docker-build.yml
.github/workflows/gradlew-sonar-analysis.yml
.github/workflows/image-transfer.yml
.github/workflows/ios-publish.yml
.github/workflows/maven-build.yml
.github/workflows/maven-publish-to-nexus.yml
.github/workflows/maven-sonar-analysis.yml
.github/workflows/npm-android-build.yml
.github/workflows/npm-build.yml
.github/workflows/npm-publish-to-npm-registry.yml
.github/workflows/npm-sonar-analysis.yml
.github/workflows/release-changes.yml
.github/workflows/tag.yaml

Signed-off-by: syed salman <syedsalman3753@gmail.com>
(cherry picked from commit a6a4e2bf0941d923047c258e7a21f609952fa375)

[DSD-4174] fixed slack notification issue for PR

---

.github/workflows/ios-build.yml

- This is a temp fix for cocoapods issue.
- Once the issue is resolved by the Github actions runner we need to remove this change.
Link for reference - https://github.com/actions/runner-images/issues/9308

Update workflow to use latest Cocoapods

---

.github/workflows/dev-pre-release-check.yaml
docs/dev-pre-release-check-readme.md

Signed-off-by: Rakshitha650 <rakshitham38@gmail.com>
(cherry picked from commit 9beb316d731740d297ff8253a608a63092800d36)

[MOSIP-30782]Developer pre release check

---

.github/workflows/chart-lint-publish.yml
.github/workflows/docker-build.yml

Signed-off-by: syed salman <syedsalman3753@gmail.com>
(cherry picked from commit 92724e2efdef1e0d999763b0a2a25f96180ad4e5)

[DSD-4989] fixed issues in docker-build.yml & chart-lint-publish.yml

---

.github/workflows/maven-build.yml
.github/workflows/maven-publish-android.yml

(cherry picked from commit 78f8496ae7645cc1faac925e4ceacff4b4fd5d65)

[DSD-5107] Added command to remove microsoft repo from apt list for maven build

---

.github/workflows/maven-sonar-analysis.yml

Need to add and test here as sonarcloud only supports java-21 now.

[MOSIP-34442]Update maven-sonar-analysis.yml

---

.github/keys/user_map.json.gpg
.github/workflows/docker-build.yml
.github/workflows/slack-notification.yml
.github/workflows/update-gpg.yml

updated resuable flow for slack notification and updating gpg for adding+revoke slack user

[MOSIP-36092] updated resuable flow for slack notification

---

.github/workflows/swift-sonar-analysis.yml

1. Added a sonar analysis yaml file for Swift.

[INJIMOB-2885]: Add swift sonar analysis

---

.github/workflows/jira-dependabot-integration.yml

Hardcoded a bot user and the project name 
Remove the secrets from github.
@ckm007

[MOSIP-39493]Updated jira-dependabot-integration.yml
